ICO framework: Neuron Class Reference
Neuron Class Reference
#include <neuron.h>
Public Member Functions
Neuron ()
~Neuron ()
void addSynapseIn (Synapse *synapse)
void addSynapseOut (Synapse *synapse)
const double & getActivity () const
const double & getBias () const
const double & getError () const
const double & getInput () const
const double & getOutput () const
Synapse * getSynapseFrom (Neuron const *pre) const
std::vector< Synapse * > getSynapsesIn () const
std::vector< Synapse * > getSynapsesOut () const
Synapse * getSynapseTo (Neuron const *post) const
void removeSynapseIn (Synapse const *synapse)
void removeSynapseOut (Synapse const *synapse)
void setActivity (const double &aactivity)
void setBias (const double &abias)
void setErrorInput (const double &aerror)
void setInput (const double &ainput)
void setOutput (const double &aoutput)
void setTransferFunction (TransferFunction const *const afunction)
void updateActivity ()
void updateError ()
void updateOutput ()
Detailed Description
Time Discrete Artificial Neuron Class
This class represents a single neuron in a time-discrete artificial neural net. It is described by its current output, activity, bias and input values as well as by the list of incoming and outgoing synapses and the transfer function to use for this neuron.
ATTENTION: All methods assume that there are no two synapses with the same postsynaptic and presynaptic neurons.
Definition at line 43 of file neuron.h.
Constructor & Destructor Documentation
Neuron::Neuron ()
the constructor
Definition at line 31 of file neuron.cpp.
Neuron::~Neuron ()
the destructor
Definition at line 42 of file neuron.cpp.
Member Function Documentation
void Neuron::addSynapseIn (Synapse * synapse)
Adds an entry to the list of incoming synapses
This method adds the given synapse to the list of incoming synapses. This does also mean that the synapse will be deleted when the neuron is. This method is called from the synapse constructor, so you do not have to (and also should not) call it manually.
Parameters
synapse pointer to the new incoming synapse
Definition at line 48 of file neuron.cpp.
References Synapse::getPre().
Referenced by Synapse::Synapse().
void Neuron::addSynapseOut (Synapse * synapse)
Adds an entry to the list of outgoing synapses
This method adds the given synapse to the list of outgoing synapses. This does also mean that the synapse will be deleted when the neuron is. This method is called from the synapse constructor, so you do not have to (and also should not) call it manually.
Parameters
synapse pointer to the new outgoing synapse
Definition at line 53 of file neuron.cpp.
References Synapse::getPost().
Referenced by Synapse::Synapse().
const double & Neuron::getActivity () const
Returns activity
This method returns the activity value of the neuron. The returned reference stays valid for the whole lifetime of the neuron.
Returns
activity value
Definition at line 58 of file neuron.cpp.
Referenced by ANN::getActivity().
const double & Neuron::getBias () const
Returns bias
This method returns the bias value of the neuron. The returned reference stays valid for the whole lifetime of the neuron.
Returns
bias value
Definition at line 63 of file neuron.cpp.
Referenced by ANN::getBias().
const double & Neuron::getError () const
Returns back propagated error
Returns
error
Definition at line 68 of file neuron.cpp.
const double & Neuron::getInput () const
Returns input
This method returns the input value of the neuron. The returned reference stays valid for the whole lifetime of the neuron.
Returns
input value
Definition at line 73 of file neuron.cpp.
const double & Neuron::getOutput () const
Returns output
This method returns the output value of the neuron. The returned reference stays valid for the whole lifetime of the neuron.
Returns
output value
Definition at line 78 of file neuron.cpp.
Referenced by ANN::getOutput().
Synapse * Neuron::getSynapseFrom (Neuron const * pre) const
Returns incoming synapse from a given neuron
This method can be used to get the synapse connecting the presynaptic neuron pre with this neuron. It is assumed that there are not two synapses connecting the same presynaptic and postsynaptic neurons. If there is no such synapse present NULL is returned.
Parameters
pre pointer to presynaptic neuron
Returns
pointer to synapse or NULL if no such synapse exists
Definition at line 83 of file neuron.cpp.
Referenced by ANN::getSynapse(), ANN::getWeight(), and ANN::setWeight().
Synapse * Neuron::getSynapseTo (Neuron const * post) const
Returns outgoing synapse to a given neuron
This method can be used to get the synapse connecting this neuron with the given postsynaptic neuron. It is assumed that there are not two synapses connecting the same presynaptic and postsynaptic neurons. If there is no such synapse present NULL is returned.
Parameters
post pointer to postynaptic neuron
Returns
pointer to synapse or NULL if no such synapse exists
Definition at line 108 of file neuron.cpp.
void Neuron::removeSynapseIn (Synapse const * synapse)
Removes an entry from the list of incoming synapses
This method removes the given synapse from the list of incoming synapses. This method is called from the synapse destructor, so you do not have to (and also should not) call it manually.
Parameters
synapse synapse to remove
Definition at line 115 of file neuron.cpp.
References Synapse::getPre().
Referenced by Synapse::~Synapse().
void Neuron::removeSynapseOut (Synapse const * synapse)
Removes an entry from the list of outgoing synapses
This method removes the given synapse from the list of outgoing synapses. This method is called from the synapse destructor, so you do not have to (and also should not) call it manually.
Parameters
synapse synapse to remove
Definition at line 122 of file neuron.cpp.
References Synapse::getPost().
Referenced by Synapse::~Synapse().
void Neuron::setActivity (const double & aactivity)
Sets the activity
This method sets the activity value of the neuron.
Parameters
aactivity new activity value
Definition at line 129 of file neuron.cpp.
Referenced by ANN::setActivity().
void Neuron::setBias (const double & abias)
Sets the bias
This method sets the bias value of the neuron.
Parameters
abias new bias value
Definition at line 134 of file neuron.cpp.
Referenced by ANN::setBias().
void Neuron::setErrorInput (const double & aerror)
Sets the error value
This method sets the error value used in back propagation algorithm
Parameters
aerror new error value
Definition at line 139 of file neuron.cpp.
void Neuron::setInput (const double & ainput)
Sets the external input
This method sets the external input value of the neuron.
Parameters
ainput new input value
Definition at line 144 of file neuron.cpp.
Referenced by ANN::setInput().
void Neuron::setOutput (const double & aoutput)
Sets the output
This method sets the output value of the neuron.
Parameters
aoutput new output value
Definition at line 149 of file neuron.cpp.
Referenced by ANN::setOutput().
void Neuron::setTransferFunction (TransferFunction const *const afunction)
Sets the transfer function
This method defines the transfer function used for this neuron. You have the possibility to define individual transfer function for every neuron of a neural net. Derive a new class from the TransferFunction class to create customn transfer functions.
Parameters
afunction pointer to the new transferFunction object
Definition at line 154 of file neuron.cpp.
Referenced by ANN::addNeuron(), and ANN::setTransferFunction().
void Neuron::updateActivity ()
Updates neural activity
This method calculates and sets the new activity value of the neuron based on the external input, the bias and the weights and the presynaptic outputs of all incoming synapses.
Definition at line 160 of file neuron.cpp.
void Neuron::updateError ()
Updates back propagated error
This method calculates the back propagated error for the neuron based on the error values of all postsynaptic neurons.
Definition at line 170 of file neuron.cpp.
References TransferFunction::derivative().
void Neuron::updateOutput ()
Updates neural output
This method calculates and sets the new output value of the neuron based on the activity value and the transfer function.
Definition at line 181 of file neuron.cpp.
The documentation for this class was generated from the following files:
/home/moro/workspace/pmanoonpong-gorobots-fork-carlos/utils/ann-framework/neuron.h
/home/moro/workspace/pmanoonpong-gorobots-fork-carlos/utils/ann-framework/neuron.cpp