ICO framework: ANN Class Reference
ANN Class Reference
#include <ann.h>
Public Member Functions
ANN ()
virtual ~ANN ()
void backpropagationStep ()
std::string dumpBiases ()
std::string dumpWeights ()
void feedForwardStep ()
const double & getActivity (const int neuron) const
std::vector< Neuron * > getAllNeurons () const
std::vector< Synapse * > getAllSynapses () const
const double & getBias (const int neuron) const
TransferFunction const * getDefaultTransferFunction () const
Neuron * getNeuron (unsigned int const index)
unsigned int getNeuronNumber () const
const double & getOutput (const int neuron) const
Synapse * getSynapse (const unsigned int &post, const unsigned int &pre) const
std::vector< Neuron * > getTopologicalSort ()
unsigned int getTotalNeuronNumber () const
const double getWeight (const int &post, const int &pre) const
const double getWeight (Neuron const *post, Neuron const *pre) const
Neuron * n (unsigned int const index)
virtual void postProcessing ()
void removeNeuron (Neuron const *neuron)
void setActivity (const int &neuron, const double &aactivity)
void setAllTransferFunctions (TransferFunction const *const func, const bool &includeSubnets=true)
void setBias (const int &neuron, const double &abias)
void setDefaultTransferFunction (TransferFunction const *const func)
void setInput (const int &neuron, const double &ainput)
void setOutput (const int &neuron, const double &aoutput)
void setTransferFunction (const int neuron, TransferFunction const *const func)
void setTransferFunction (Neuron *neuron, TransferFunction const *const func)
void setWeight (const int post, const int pre, const double weight)
virtual void step ()
virtual void updateActivities ()
virtual void updateOutputs ()
bool updateTopologicalSort ()
virtual void updateWeights ()
Static Public Member Functions
static const double & getActivity (Neuron const *neuron)
static const double & getBias (Neuron const *neuron)
static const double & getOutput (Neuron const *neuron)
static Synapse * getSynapse (Neuron const *const post, Neuron const *const pre)
static LinearFunction const *const identityFunction ()
static ThresholdFunction const *const thresholdFunction ()
static LogisticFunction const *const logisticFunction ()
static void setActivity (Neuron *neuron, const double &aactivity)
static void setBias (Neuron *neuron, const double &abias)
static void setInput (Neuron *neuron, const double ainput)
static void setOutput (Neuron *neuron, const double aoutput)
static void setWeight (Neuron *post, Neuron *pre, const double weight)
static TanhFunction const *const tanhFunction ()
Protected Member Functions
void setNeuronNumber (const unsigned int &anumber)
Neuron * addNeuron ()
void addSubnet (ANN *subnet)
void b (const int neuron, const double &abias)
void b (Neuron *neuron, const double &abias)
const double & b (const int neuron)
void w (const int &post, const int &pre, const double &aweight)
void w (Neuron *post, Neuron *pre, const double &aweight)
const double w (const int &post, const int &pre)
Static Protected Member Functions
static Synapse * addSynapse (Neuron *post, Neuron *pre)
Detailed Description
Artificial Neural Network Class
This is a class to represent a time-discrete recurrent neural network. You can subclass this class to obtain classes for special network configurations (such as VRN, PSN, CPG ...). It should be sufficient to include this file into your project. Under normal circumstances you don't need to know anything about the underlying neuron and synapses classes.
Definition at line 42 of file ann.h.
Constructor & Destructor Documentation
ANN::ANN ()
The constructor.
Definition at line 40 of file ann.cpp.
References setDefaultTransferFunction().
ANN::~ANN () virtual
The destructor.
Definition at line 45 of file ann.cpp.
References setNeuronNumber().
Member Function Documentation
Neuron * ANN::addNeuron () protected
Adds a neuron to the network
This methods creates a new neuron and adds it to the network.
Returns
pointer to the newly created neuron
Definition at line 54 of file ann.cpp.
References Neuron::setTransferFunction().
Referenced by ICO::ICO(), and setNeuronNumber().
void ANN::addSubnet (ANN * subnet) protected
Adds a sub network to this network
This method adds the given network as a sub network of this network. This basically means that activities, outputs and weights are updated synchronously
Parameters
subnet Pointer to the ANN that should be added as sub network
Definition at line 62 of file ann.cpp.
Synapse * ANN::addSynapse (Neuron * post, Neuron * pre) static protected
Adds a synapse between two neurons
This method creates a new synapse between the two given neurons.
Parameters
post pointer to the postsynaptic neuron
pre pointer to the presynaptic neuron
Returns
pointer to the newly created synapse
Definition at line 67 of file ann.cpp.
Referenced by setWeight().
void ANN::b (const int neuron, const double & abias) protected
Sets the bias of a neuron of this network
This method is an abbreviation of ANN::setBias(int, double).
Parameters
neuron index of the neuron
abias new bias value of this neuron
Definition at line 73 of file ann.cpp.
References setBias().
void ANN::b (Neuron * neuron, const double & abias) protected
Sets the bias of a any neuron
This method is an abbreviation of ANN::setBias(Neuron*, double).
Parameters
neuron pointer to the neuron
abias new bias value of this neuron
Definition at line 78 of file ann.cpp.
References setBias().
const double & ANN::b (const int neuron) protected
Returns the bias of a neuron of this network
This method is an abbreviation of ANN::getBias(int).
Parameters
neuron index of the neuron
Returns
bias value of the neuron
Definition at line 83 of file ann.cpp.
References getBias().
const double & ANN::getActivity (const int neuron) const
Returns the activity of the neuron with the given number
This method can be used to get the activity value of the neuron with the given number directly belonging to this network. You cannot access the activity values of neurons of other networks or subnetworks with this method. If this is necessary use the method of the specific network or ANN::getBias(Neuron*) with a pointer to the desired neuron instead.
Parameters
neuron index of the neuron
Returns
activity value
Definition at line 132 of file ann.cpp.
const double & ANN::getActivity (Neuron const * neuron) static
Returns the activity of the given neuron
You can use this function to retrieve the activity of any neuron without having to include the neuron.h header file. If you don't mind including the additional header you can as well use Neuron::getActivity().
Parameters
neuron pointer to the neuron
Returns
activity value
Definition at line 136 of file ann.cpp.
References Neuron::getActivity().
std::vector< Neuron * > ANN::getAllNeurons () const
Returns all neurons
This method returns a vector with pointers to all neurons in this network and all of its sub networks
Returns
vector containing pointers to all neurons
Definition at line 141 of file ann.cpp.
Referenced by updateTopologicalSort().
const double & ANN::getBias (const int neuron) const
Returns the bias of the neuron with the given number
This method can be used to get the bias value of the neuron with the given number directly belonging to this network. You cannot access the bias values of neurons of other networks or subnetworks with this method. If this is necessary use the method of the specific network or ANN::getBias(Neuron*) with a pointer to the desired neuron instead.
Parameters
neuron index of the neuron
Returns
bias value
Definition at line 170 of file ann.cpp.
Referenced by b().
const double & ANN::getBias (Neuron const * neuron) static
Returns the bias of the given neuron
You can use this function to retrieve the bias of any neuron without having to include the neuron.h header file. If you don't mind including the additional header you can as well use Neuron::getBias().
Parameters
neuron pointer to the neuron
Returns
bias value
Definition at line 174 of file ann.cpp.
References Neuron::getBias().
TransferFunction const * ANN::getDefaultTransferFunction () const
Returns a pointer to the default transfer function of the network
Returns
pointer to the default transfer function
Definition at line 179 of file ann.cpp.
Neuron * ANN::getNeuron (unsigned int const index)
Returns a pointer to the neuron with the given number
This method can be used to get direct access to a neuron belonging to this network or to store a pointer to a specific neuron when working with multiple or sub networks.
Parameters
index index of the neuron
Returns
pointer to the neuron
Definition at line 184 of file ann.cpp.
Referenced by n().
unsigned int ANN::getNeuronNumber () const
Returns the number of neurons of this network
This method returns the number of neurons directly belonging to this network. Neurons of sub networks are not considered. Use ANN::getTotalNeuronNumber() instead if you want to consider neurons of all sub networks as well.
Returns
number of neurons
Definition at line 189 of file ann.cpp.
Referenced by ICO::setPredictiveNeuronInput().
const double & ANN::getOutput (const int neuron) const
Returns the output of the neuron with the given number
This method can be used to get the output value of the neuron with the given number directly belonging to this network. You cannot access the output values of neurons of other networks or subnetworks with this method. If this is necessary use the method of the specific network or ANN::getOutput(Neuron*) with a pointer to the desired neuron instead.
Parameters
neuron index of the neuron
Returns
output value
Definition at line 194 of file ann.cpp.
Referenced by ICO::getOutputNeuronOutput().
const double & ANN::getOutput (Neuron const * neuron) static
Returns the output of the given neuron
You can use this function to retrieve the output of any neuron without having to include the neuron.h header file. If you don't mind including the additional header you can as well use Neuron::getOutput().
Parameters
neuron pointer to the neuron
Returns
output value
Definition at line 199 of file ann.cpp.
References Neuron::getOutput().
Synapse * ANN::getSynapse (const unsigned int & post, const unsigned int & pre) const
Returns synapse between two neurons of this network
This methods returns the synapse between the given presynaptic and postsynaptic neuron directly belonging to this network. If no such synapse exists NULL is returned.
Parameters
post index of postsynaptic neuron
pre index of presynaptic neuron
Returns
pointer to synapse or NULL if not existent
Definition at line 204 of file ann.cpp.
Synapse * ANN::getSynapse (Neuron const *const post, Neuron const *const pre) static
Returns synapse between any two neurons
This method returns the synapse between the given presynaptic and postsynaptic neuron that do not have to belong to the same network. If no such synapse exists NULL is returned.
Parameters
post pointer to postsynaptic neuron
pre pointer to presynaptic neuron
Returns
pointer to synapse or NULL if not existent
Definition at line 210 of file ann.cpp.
References Neuron::getSynapseFrom().
std::vector< Neuron * > ANN::getTopologicalSort ()
Returns the topological sort
This method can be used to obtain the topological sort of all neurons in a feed forward network. The result is undefined if the network is not a feed forward network
Returns
vector representing the topological sort
Definition at line 215 of file ann.cpp.
unsigned int ANN::getTotalNeuronNumber () const
Returns the number of neurons of this network including sub networks
This method returns the number of neurons belonging to this network and all of its sub networks (and their sub networks and so on...). Use ANN::getNeuronNumber() instead if you only want to know the number of neurons belonging directly to this network (without considering sub networks).
Returns
number of neurons
Definition at line 220 of file ann.cpp.
const double ANN::getWeight (const int & post, const int & pre) const
Returns the weight of the synapse between two neurons of this network
This method returns the weight of the synapse between two neurons defined by their indexes or 0 if their is no such synapse. This only works for neurons directly belonging to this network. If you want to retrieve synaptic weights between neurons of different or sub networks you have to use ANN::getWeight(Neuron*, Neuron*).
Parameters
post index of the postsynaptic neuron
pre index of the presynaptic neuron
Postcondition
weight of the synapse (or 0 if not present)
Definition at line 230 of file ann.cpp.
Referenced by ICO::getWeights(), ICO::updateWeights(), and w().
const double ANN::getWeight (Neuron const * post, Neuron const * pre) const
Returns the weight of the synapse between any two neurons
This method returns the weight of the synapse between the two given neurons or 0 if their is no such synapse. For neurons directly belonging to the same network you can as well use ANN::getWeight(int, int).
Parameters
post pointer to the postsynaptic neuron
pre pointer to the presynaptic neuron
Returns
weight of the synapse (or 0 if not present)
Definition at line 235 of file ann.cpp.
References Neuron::getSynapseFrom(), and Synapse::getWeight().
LinearFunction const *const ANN::identityFunction () static
Return pointer to a identity function object
Returns
pointer to identity function object
Definition at line 248 of file ann.cpp.
Referenced by ICO::ICO().
LogisticFunction const *const ANN::logisticFunction () static
Return pointer to a LogisticFunction object
Returns
pointer to LogisticFunction object
Definition at line 256 of file ann.cpp.
Neuron * ANN::n (unsigned int const index)
Returns a pointer to the neuron with the given number
This is an abbreviation for Neuron* getNeuron(unsigned int const index)
Parameters
index index of the neuron
Returns
pointer to the neuron
Definition at line 243 of file ann.cpp.
References getNeuron().
Referenced by updateTopologicalSort().
void ANN::postProcessing () virtual
Do stuff at the end of simulation step
When using ANN::step() this method is called in every simulation step after updating the neuron outputs. Overload it if you need to do some stuff in every time step. The default implementation does nothing.
Definition at line 260 of file ann.cpp.
Referenced by step().
void ANN::removeNeuron (Neuron const * neuron)
Removes neuron from the network
This method removes the given neuron from the network. All the synapses attached to the neuron are removed as well. The neuron is only removed if it indeed belongs to the network on which this method was called.
Parameters
neuron pointer to the neuron
Todo:
give out error message if neuron does not belong to this net
Definition at line 265 of file ann.cpp.
Referenced by setNeuronNumber().
void ANN::setActivity (const int & neuron, const double & aactivity)
Sets the activity of the neuron with the given index
This method can be used to set the activity value of the neuron with the given index directly belonging to this network. You cannot set the activity values of neurons of other networks or subnetworks with this method. If this is necessary use the method of the specific network or ANN::setActivity(Neuron*,double) with a pointer to the desired neuron instead.
Parameters
neuron index of the neuron
aactivity new activity value
Definition at line 275 of file ann.cpp.
void ANN::setActivity (Neuron * neuron, const double & aactivity) static
Sets the input of the given neuron
You can use this function to set the activity of any neuron without having to include the neuron.h header file. If you don't mind including the additional header you can as well use Neuron::setActivity(double).
Parameters
neuron pointer to the neuron
aactivity new activity value
Definition at line 280 of file ann.cpp.
References Neuron::setActivity().
void ANN::setAllTransferFunctions (TransferFunction const *const func, const bool & includeSubnets = true)
Sets the transfer functions of all neurons
With this method you can set the transfer function used for all neurons. You can decide whether also the transfer functions of neurons belonging to subnets should be included in the setting. If you want to change also which transfer function will be used for neurons added in the future use ANN::setDefaultTransferFunction()
Parameters
func pointer to the TransferFunction object
includeSubnets decides whether neurons of subnets are also affected
Definition at line 285 of file ann.cpp.
void ANN::setBias (Neuron * neuron, const double & abias) static
Sets the bias of the given neuron
You can use this function to set the bias of any neuron without having to include the neuron.h header file. If you don't mind including the additional header you can as well use Neuron::setBias(double).
Parameters
neuron pointer to the neuron
abias new bias value
Definition at line 301 of file ann.cpp.
References Neuron::setBias().
Referenced by b(), and setBias().
void ANN::setBias (const int & neuron, const double & abias)
Sets the bias of the neuron with the given index
This method can be used to set the bias of the neuron with the given index directly belonging to this network. You cannot set the bias values of neurons of other networks or subnetworks with this method. If this is necessary use the method of the specific network or ANN::setBias(Neuron*) with a pointer to the desired neuron instead.
Parameters
neuron index of the neuron
abias new bias value
Definition at line 306 of file ann.cpp.
References setBias().
void ANN::setDefaultTransferFunction (TransferFunction const *const func)
Sets the default transfer function of this network
With this method you can define the default transfer function used for new neurons of this network. This only affects neurons which are created after calling ANN::setDefaultTransferFunction().
Parameters
func pointer to the new default transfer function
Definition at line 311 of file ann.cpp.
Referenced by ANN(), and ICO::ICO().
void ANN::setInput (const int & neuron, const double & ainput)
Sets the input of the neuron with the given index
This method can be used to set the external input to the neuron with the given index directly belonging to this network. You cannot set the input values of neurons of other networks or subnetworks with this method. If this is necessary use the method of the specific network or ANN::setInput(Neuron*,double) with a pointer to the desired neuron instead.
Parameters
neuron index of the neuron
ainput new input value
Definition at line 316 of file ann.cpp.
Referenced by ICO::setInputNeuronInput().
void ANN::setInput (Neuron * neuron, const double ainput) static
Sets the input of the given neuron
You can use this function to set the input of any neuron without having to include the neuron.h header file. If you don't mind including the additional header you can as well use Neuron::setInput(double).
Parameters
neuron pointer to the neuron
ainput new input value
Definition at line 321 of file ann.cpp.
References Neuron::setInput().
void ANN::setNeuronNumber (const unsigned int & anumber) protected
Defines the neuron number of this network
With this function you can set the desired number of neurons for this network. If less neurons are currently present neurons are added, if more neurons are present the neurons with the highest indexes are removed.
Parameters
anumber new number of neurons directly belonging to this net
Definition at line 336 of file ann.cpp.
References addNeuron(), and removeNeuron().
Referenced by ~ANN().
void ANN::setOutput (const int & neuron, const double & aoutput)
Sets the output of the neuron with the given index
This method can be used to set the output value of the neuron with the given index directly belonging to this network. You cannot set the output values of neurons of other networks or subnetworks with this method. If this is necessary use the method of the specific network or ANN::setOutput(Neuron*,double) with a pointer to the desired neuron instead.
Parameters
neuron index of the neuron
aoutput new output value
Definition at line 326 of file ann.cpp.
void ANN::setOutput (Neuron * neuron, const double aoutput) static
Sets the output of the given neuron
You can use this function to set the output value of any neuron without having to include the neuron.h header file. If you don't mind including the additional header you can as well use Neuron::setOutput(double).
Parameters
neuron pointer to the neuron
aoutput new output value
Definition at line 331 of file ann.cpp.
References Neuron::setOutput().
void ANN::setTransferFunction (const int neuron, TransferFunction const *const func)
Sets transfer function for a neuron of this net
This method allows you to set an individual transfer function for a neuron belonging to this network. You cannot set the transfer function of neurons of other networks or subnetworks with this method. If this is necessary use the method of the specific network or ANN::setTransferFunction(Neuron*,TransferFunction) with a pointer to the desired neuron instead.
Parameters
neuron index of the neuron
func pointer to the transfer function object
Definition at line 352 of file ann.cpp.
void ANN::setTransferFunction (Neuron * neuron, TransferFunction const *const func)
Sets the transfer function of the given neuron
You can use this function to set the transfer function of any neuron without having to include the neuron.h header file. If you don't mind including the additional header you can as well use Neuron::setTransferFunction(TransferFunction*).
Parameters
neuron pointer to the neuron
func pointer to the transfer function object
Definition at line 358 of file ann.cpp.
References Neuron::setTransferFunction().
void ANN::setWeight (Neuron * post, Neuron * pre, const double weight) static
Sets the weight of the synapse between any two neurons
Use this method to set the weight of the synapse between any two given neurons. The neurons do not have to belong to the same network. If a synapse between those two neurons already exists its weight is altered. If no synapse exists a new synapse with the given weight is created. For neurons directly belonging to the same network you can as well use ANN::setWeight(int, int, double).
Parameters
post pointer to the postsynaptic neuron
pre pointer to the presynaptic neuron
weight new weight of the synapse
Definition at line 365 of file ann.cpp.
References addSynapse(), Neuron::getSynapseFrom(), and Synapse::setWeight().
Referenced by setWeight(), ICO::updateWeights(), and w().
void ANN::setWeight (const int post, const int pre, const double weight)
Sets the weight of the synapse between two neurons of this network
Use this method to set the weight of the synapse between the neurons with the defined indexes of this network. If a synapse between those two neurons already exists its weight is altered. If no synapse exists a new synapse with the given weight is created. For belonging to different networks use ANN::setWeight(Neuron*, Neuron*, double).
Parameters
post index of the postsynaptic neuron
pre index of the presynaptic neuron
weight new weight of the synapse
Definition at line 372 of file ann.cpp.
References setWeight().
void ANN::step () virtual
Does one simulation step
This a convenience function which calls the following functions in the given order:
ANN::updateActivities()
ANN::updateWeights()
ANN::updateOutputs()
Reimplemented in ICO.
Definition at line 377 of file ann.cpp.
References postProcessing(), updateActivities(), updateOutputs(), and updateWeights().
TanhFunction const *const ANN::tanhFunction () static
Returns pointer to a TanhFunction object
Returns
pointer to TanhFunction object
Definition at line 348 of file ann.cpp.
ThresholdFunction const *const ANN::thresholdFunction () static
Return pointer to a threshold function object
Returns
pointer to threshold function object
Definition at line 252 of file ann.cpp.
void ANN::updateActivities () virtual
Updates neuron activities
This method iterates over all neurons in this network and all sub networks and updates their activity values based on all incoming synaptic weights and the presynaptic outputs.
Definition at line 385 of file ann.cpp.
Referenced by ICO::step(), and step().
void ANN::updateOutputs () virtual
Updates neuron outputs
This method iterates over all neurons in this network and all sub networks and updates their output values based on their activity values.
Definition at line 397 of file ann.cpp.
Referenced by ICO::step(), and step().
bool ANN::updateTopologicalSort ()
Update the topological sort
This method updates the topological sort of the neurons in this network. As a topological sort only exists for feed-forward networks, this method returns false if the creation of the sort fails indicating that there exists a loop in the network
Returns
boolean value indicating if network is feed-forward
Definition at line 409 of file ann.cpp.
References getAllNeurons(), and n().
void ANN::updateWeights () virtual
Updates synaptic weights
This method can be overriden if you want to include synaptic plasticity. The default implementation does nothing.
Reimplemented in ICO.
Definition at line 456 of file ann.cpp.
Referenced by step().
void ANN::w (const int & post, const int & pre, const double & aweight) protected
Sets the synaptic weight between two neurons of this network
This method is an abbreviation of ANN::setWeight(int,int,double).
Parameters
post index of the postsynaptic neuron
pre index of the presynaptic neuron
aweight new weight of the synapse
Definition at line 464 of file ann.cpp.
References setWeight().
Referenced by ICO::ICO().
void ANN::w (Neuron * post, Neuron * pre, const double & aweight) protected
Sets the synaptic weight between any two neurons
This method is an abbreviation of ANN::setWeight(Neuron*,Neuron*,double).
Parameters
post pointer to the postsynaptic neuron
pre pointer to the presynaptic neuron
aweight new weight of the synapse
Definition at line 469 of file ann.cpp.
References setWeight().
const double ANN::w (const int & post, const int & pre) protected
Returns the weight of a synapse between two neurons of this network
This method is an abbreviation of ANN::getWeight(int,int).
Parameters
post index of the postsynaptic neuron
pre index of the presynaptic neuron
Returns
synaptic weight or 0 if synapse not present
Definition at line 475 of file ann.cpp.
References getWeight().
The documentation for this class was generated from the following files:
/home/moro/workspace/pmanoonpong-gorobots-fork-carlos/utils/ann-framework/ann.h
/home/moro/workspace/pmanoonpong-gorobots-fork-carlos/utils/ann-framework/ann.cpp