ICO framework: Synapse Class Reference
Synapse Class Reference
#include <synapse.h>
Public Member Functions
Synapse (Neuron *const apost, Neuron *const apre, const bool &connect=true)
~Synapse ()
Neuron * getPost () const
Neuron * getPre () const
const double & getWeight () const
void setWeight (const double &aweight)
Detailed Description
Synapse Class
This class represents a single directed synapse connection to neurons of an artificial neural net. The synapse is described by the pre- and postsynaptic neuron and its synaptic weight.
Definition at line 34 of file synapse.h.
Constructor & Destructor Documentation
Synapse::Synapse (Neuron *const apost, Neuron *const apre, const bool & connect = true)
The constructor
You have to give the pre- and postsynaptic neuron here. Those cannot be changed later. Create a new synapse if you want to connect other neurons instead of the present ones.
The constructor also "registers" the new synapse at the two neurons so that the synapse is inserted into their corresponding lists.
Parameters
apost pointer to the postsynaptic neuron
apre pointer to the presynaptic neuron
connect if true, the synapse will register itself at the two neurons it connects
Definition at line 25 of file synapse.cpp.
References Neuron::addSynapseIn(), and Neuron::addSynapseOut().
Synapse::~Synapse ()
The destructor
The destructor also removes the synapse from the corresponding synapse lists of the post- and presynaptic neuron.
Definition at line 37 of file synapse.cpp.
References Neuron::removeSynapseIn(), and Neuron::removeSynapseOut().
Member Function Documentation
Neuron * Synapse::getPost () const
Returns postsynaptic neuron
Returns
pointer to the postsynaptic neuron
Definition at line 43 of file synapse.cpp.
Referenced by Neuron::addSynapseOut(), and Neuron::removeSynapseOut().
Neuron * Synapse::getPre () const
Returns presynaptic neuron
Returns
pointer to the presynaptic neuron
Definition at line 48 of file synapse.cpp.
Referenced by Neuron::addSynapseIn(), and Neuron::removeSynapseIn().
const double & Synapse::getWeight () const
Returns synaptic weight
This method returns the weight of this synapse. The reference stays valid for the whole lifetime of the synapse.
Returns
synaptic weight
Definition at line 53 of file synapse.cpp.
Referenced by ANN::getWeight().
void Synapse::setWeight (const double & aweight)
Sets synaptic weight
This method can be used to alter the weight of this synapse.
Parameters
aweight new synaptic weight
Definition at line 58 of file synapse.cpp.
Referenced by ANN::setWeight().
The documentation for this class was generated from the following files:
/home/moro/workspace/pmanoonpong-gorobots-fork-carlos/utils/ann-framework/synapse.h
/home/moro/workspace/pmanoonpong-gorobots-fork-carlos/utils/ann-framework/synapse.cpp