ICO framework: ICO Class Reference
ICO Class Reference
#include <ico.h>
Public Member Functions
ICO ()
ICO (const double &rate)
ICO (const int &neuronNumber, const double &rate)
virtual ~ICO ()
virtual void step ()
void setReflexiveNeuronInput (const double &value)
void setPredictiveNeuronInput (const int &index, const double &value)
void setPredictiveNeuronInput (std::vector< double > &values)
const double & getOutputNeuronOutput ()
std::vector< double > getWeights ()
Public Member Functions inherited from ANN
ANN ()
virtual ~ANN ()
void backpropagationStep ()
std::string dumpBiases ()
std::string dumpWeights ()
void feedForwardStep ()
const double & getActivity (const int neuron) const
std::vector< Neuron * > getAllNeurons () const
std::vector< Synapse * > getAllSynapses () const
const double & getBias (const int neuron) const
TransferFunction const * getDefaultTransferFunction () const
Neuron * getNeuron (unsigned int const index)
unsigned int getNeuronNumber () const
const double & getOutput (const int neuron) const
Synapse * getSynapse (const unsigned int &post, const unsigned int &pre) const
std::vector< Neuron * > getTopologicalSort ()
unsigned int getTotalNeuronNumber () const
const double getWeight (const int &post, const int &pre) const
const double getWeight (Neuron const *post, Neuron const *pre) const
Neuron * n (unsigned int const index)
virtual void postProcessing ()
void removeNeuron (Neuron const *neuron)
void setActivity (const int &neuron, const double &aactivity)
void setAllTransferFunctions (TransferFunction const *const func, const bool &includeSubnets=true)
void setBias (const int &neuron, const double &abias)
void setDefaultTransferFunction (TransferFunction const *const func)
void setInput (const int &neuron, const double &ainput)
void setOutput (const int &neuron, const double &aoutput)
void setTransferFunction (const int neuron, TransferFunction const *const func)
void setTransferFunction (Neuron *neuron, TransferFunction const *const func)
void setWeight (const int post, const int pre, const double weight)
virtual void updateActivities ()
virtual void updateOutputs ()
bool updateTopologicalSort ()
Protected Member Functions
virtual void updateWeights ()
void setInputNeuronInput (const int &index, const double &value)
Protected Member Functions inherited from ANN
void setNeuronNumber (const unsigned int &anumber)
Neuron * addNeuron ()
void addSubnet (ANN *subnet)
void b (const int neuron, const double &abias)
void b (Neuron *neuron, const double &abias)
const double & b (const int neuron)
void w (const int &post, const int &pre, const double &aweight)
void w (Neuron *post, Neuron *pre, const double &aweight)
const double w (const int &post, const int &pre)
Additional Inherited Members
Static Public Member Functions inherited from ANN
static const double & getActivity (Neuron const *neuron)
static const double & getBias (Neuron const *neuron)
static const double & getOutput (Neuron const *neuron)
static Synapse * getSynapse (Neuron const *const post, Neuron const *const pre)
static LinearFunction const *const identityFunction ()
static ThresholdFunction const *const thresholdFunction ()
static LogisticFunction const *const logisticFunction ()
static void setActivity (Neuron *neuron, const double &aactivity)
static void setBias (Neuron *neuron, const double &abias)
static void setInput (Neuron *neuron, const double ainput)
static void setOutput (Neuron *neuron, const double aoutput)
static void setWeight (Neuron *post, Neuron *pre, const double weight)
static TanhFunction const *const tanhFunction ()
Static Protected Member Functions inherited from ANN
static Synapse * addSynapse (Neuron *post, Neuron *pre)
Detailed Description
Definition of the ICO class.
This class is based on the artificial neural network class (ANN). It defines and modifies the parameters and methods needed for implementing an ICO learning class out of that one.
Definition at line 20 of file ico.h.
Constructor & Destructor Documentation
ICO::ICO ()
Class default constructor.
Definition at line 10 of file ico.cpp.
References ANN::addNeuron(), ANN::identityFunction(), ANN::setDefaultTransferFunction(), and ANN::w().
ICO::ICO (const double & rate)
Class basic constructor.
This constructor creates a basic ICO network with 2 inputs as shown below. Being P the predictive input , R the reflexive input and O the output.
Parameters
rate The learning rate of the network.
Definition at line 30 of file ico.cpp.
References ANN::addNeuron(), ANN::identityFunction(), ANN::setDefaultTransferFunction(), and ANN::w().
ICO::ICO (const int & neuronNumber, const double & rate)
Class constructor for bigger networks.
This constructor allows to create an ICO network with as many predictive inputs as desired and a reflexive input as shown below. P1 to Pn are the predictive inputs, R the reflexive input and O the output.
Parameters
neuronNumber Number of predictive neurons in the network. It has to be equal or bigger than 1.
rate The learning rate of the network.
Definition at line 50 of file ico.cpp.
References ANN::addNeuron(), ANN::identityFunction(), ANN::setDefaultTransferFunction(), and ANN::w().
ICO::~ICO () virtual
Default class destructor.
Definition at line 70 of file ico.cpp.
Member Function Documentation
const double & ICO::getOutputNeuronOutput ()
Function to get the output of the system.
This function returns the output of the network.
Returns
Double containing the output of the network.
Definition at line 97 of file ico.cpp.
References ANN::getOutput().
std::vector< double > ICO::getWeights ()
Function to retrieve the synaptic weights of the neurons.
Returns
Vector of doubles containing the weights, starting with the reflexive one.
Definition at line 101 of file ico.cpp.
References ANN::getWeight().
void ICO::setInputNeuronInput (const int & index, const double & value) protected
Method that sets the input value of the neurons.
Auxiliar method that sets the inputs of the neurons. If the index is 0 it sets the input of the reflexive neuron. Any other value sets the corresponding predictive neuron.
Parameters
index Index of the neuron whose input is set. 0 for the reflexive.
value Double containing the input value for the neuron.
Definition at line 89 of file ico.cpp.
References ANN::setInput().
Referenced by setPredictiveNeuronInput(), and setReflexiveNeuronInput().
void ICO::setPredictiveNeuronInput (const int & index, const double & value)
Function for setting the input of a single predictive neuron.
This function sets the input value for an individual predictive neuron. This function has to be called before the ICO::step function for every predictive neuron in the network.
Parameters
index Number of the predictive neuron whose input is set. Starts in 0.
value Double containing the input value for the predictive neuron.
Definition at line 115 of file ico.cpp.
References setInputNeuronInput().
void ICO::setPredictiveNeuronInput (std::vector< double > & values)
Function for setting the input of the predictive neurons of the network.
This function sets the input value of all the predictive neurons. This function has to be called before the ICO::step function.
Parameters
values Vector of doubles containing the inputs for all the predictive neurons. It has to be the same size as predictive neurons contains the network.
Definition at line 119 of file ico.cpp.
References ANN::getNeuronNumber(), and setInputNeuronInput().
void ICO::setReflexiveNeuronInput (const double & value)
Function for setting the input of the reflexive neuron.
This function has to be called before the ICO::step function to set the reflexive neuron value.
Parameters
value Double containing the input value for the reflexive neuron.
Definition at line 111 of file ico.cpp.
References setInputNeuronInput().
void ICO::step () virtual
Redefinition of the ANN::step method for the class.
This method calls the methods ANN::updateActivities, ANN::updateOutputs and ICO::updateWeights in this order.
Reimplemented from ANN.
Definition at line 73 of file ico.cpp.
References ANN::updateActivities(), ANN::updateOutputs(), and updateWeights().
void ICO::updateWeights () protected virtual
Redefinition of the ANN::updateWeights method for the class.
This method updates the weights of the network based on the correlation in between the reflexive input and the predictive inputs. Only the weights of the predictive inputs are changed, while the reflexive one stays in 1.0 forever.
Reimplemented from ANN.
Definition at line 79 of file ico.cpp.
References ANN::getWeight(), and ANN::setWeight().
Referenced by step().
The documentation for this class was generated from the following files:
ico.h
ico.cpp