# Configuration for simulation makefile
# Please add all cpp files you want to compile for this simulation
#  to the FILES variable
# You can also tell where you haved lpzrobots installed

#LIBSELFORG=$(shell selforg-config $(CFGOPTS) --libfile)
#LIBSELFORGSHARED:=$(shell selforg-config $(CFGOPTS) --solibfile)
SELFORGSRCPREFIX=$(shell selforg-config $(CFGOPTS) --srcprefix)  #selforg directory

#LIBODEROBOTS=$(shell ode_robots-config $(CFGOPTS) --libfile)
#LIBODEROBOTSSHARED:=$(shell ode_robots-config $(CFGOPTS) --solibfile)
ODEROBOTSSRCPREFIX=$(shell ode_robots-config $(CFGOPTS) --srcprefix)  #ode_robots directory

GOROBOTS    = ../../../../../..
LPZROBOTS	= $(ODEROBOTSSRCPREFIX)/..
AMOSIIUTIL  = $(GOROBOTS)/utils
AMOSIICONT  = $(GOROBOTS)/projects/amosii/koh_preview_neuralcontrol/amosiiv2_neuralcontrol_rc/each_fm_each_gait/controllers
AMOSIIREAL= $(LPZROBOTS)/real_robots/robots/amosii




FILES      += main \
			  $(AMOSIIUTIL)/esn-framework/networkmatrix \
 			  $(AMOSIIREAL)/cmdline \
 			  $(AMOSIIREAL)/console \
 			  $(AMOSIIREAL)/amosIIserialv1 \
 			  $(AMOSIIREAL)/amosIIserialv2 \
			  $(AMOSIICONT)/amosIIcontrol \
			  $(AMOSIICONT)/NeuralPreprocessingReflex \
			  $(AMOSIICONT)/NeuralLearningAndMemoryYourExtension \
			  $(AMOSIICONT)/NeuralLocomotionControlAdaptiveClimbing \

INC        += -I $(GOROBOTS)/projects/amosii/koh_preview_neuralcontrol/amosiiv2_neuralcontrol_rc/each_fm_each_gait/controllers
INC        += -I$(AMOSIIREAL)
INC        += -I$(AMOSIIUTIL)

LIBS       = -lreadline  -lncurses
# add this to avoid problem for 64 bit PC
LIBS = -Wl,--no-as-needed -lgsl -lgslcblas -lm




