# Configuration for simulation makefile
# Please add all cpp files you want to compile for this simulation
#  to the FILES variable
# You can also tell where you haved lpzrobots installed

ODEROBOTSSRCPREFIX=$(shell ode_robots-config $(CFGOPTS) --srcprefix)  #ode_robots directory
SELFORGSRCPREFIX=$(shell selforg-config $(CFGOPTS) --srcprefix)  #selforg directory

LPZROBOTS   = $(ODEROBOTSSRCPREFIX)/..

#GOROBOTS    = ../../..
#UTILS       = $(GOROBOTS)/controller/utils
#ANN_FRM     = $(UTILS)/ann-framework
#ANN_LIB     = $(UTILS)/ann-library

FILES      += main
              

INC        += -I

LIBS       = -lreadline  -lncurses	
