# Configuration for simulation makefile
# Please add all cpp files you want to compile for this simulation
#  to the FILES variable
# You can also tell where you haved lpzrobots installed

GOROBOTS    = ../../..
UTILS       = $(GOROBOTS)/utils
ANN_FRM     = $(UTILS)/ann-framework
ANN_LIB     = $(UTILS)/ann-library

FILES      += main \
              examplecontroller \
              $(ANN_FRM)/ann \
              $(ANN_FRM)/neuron \
              $(ANN_FRM)/synapse \
              $(ANN_LIB)/so2cpg \
              $(ANN_LIB)/vrn \
              $(ANN_LIB)/psn \
              $(UTILS)/interpolator2d

INC        += -I$(GOROBOTS)