# Configuration for simulation makefile
# Please add all cpp files you want to compile for this simulation
#  to the FILES variable
# You can also tell where you haved lpzrobots installed


ODEROBOTSSRCPREFIX=$(shell ode_robots-config $(CFGOPTS) --srcprefix)  #ode_robots directory
SELFORGSRCPREFIX=$(shell selforg-config $(CFGOPTS) --srcprefix)  #selforg directory

MAINDIR   = ../../../..
NIMMFILE  = $(MAINDIR)/utils/sim_robots/nimm4ii_v1
LPZROBOTS   = $(ODEROBOTSSRCPREFIX)/..
AMOSIIUTIL  = $(MAINDIR)/utils

FILES      += main \
              $(NIMMFILE)/fourwheeledrpos \
              $(NIMMFILE)/relativepositionsensor \
			 $(AMOSIIUTIL)/ann-framework/ann\
			 $(AMOSIIUTIL)/ann-framework/neuron\
			 $(AMOSIIUTIL)/ico-framework/ico\
			 $(AMOSIIUTIL)/ann-framework/synapse
			 
			

INC        += -I$(MAINDIR)
INC        += -I$(NIMMFILE)

LIBS       = -lreadline  -lncurses



