Evolutionary algorithm framework: EA< T > Class Template Reference
EA< T > Class Template Reference
#include <ea.h>
Public Member Functions
EA (int population, int size, encoding_type chromosome_encoding, T min, T max, crossover_type crossover, double crossover_rate, mutation_type mutation, double mutation_rate, selection_type selection, int selection_size, replacement_type replacement)
~EA ()
void setFitnessFunction (double(*function)(Chromosome< T > *))
void setFitnessFunction (double(*function)(Chromosome< T > *, int argc, char **argv))
void randomInitialization ()
void initializePopulation (std::vector< Chromosome< T > * > initial_population)
void printPopulation ()
void evaluate ()
void evaluateOffspring ()
void evaluateThreaded (unsigned int threads)
void evaluateOffspringThreaded (unsigned int threads)
double evaluateOne (Chromosome< T > *i)
void select ()
void reproduce ()
void replace ()
void evolve (unsigned int generations, int solution)
Chromosome< T > * evolve (unsigned int generations)
Chromosome< T > * evolveThreaded (unsigned int generations, unsigned int threads)
Protected Attributes
std::vector< Chromosome< T > * > population
Vector containing pointers all the chromosomes for the actual population.
std::vector< Chromosome< T > * > selected
Vector containing pointers to the selected chromosomes for crossover.
std::vector< Chromosome< T > * > offspring
Vector containing pointers to the chromosomes resultant of the crossover.
unsigned int population_size
Size of the population.
unsigned int Chromosome_size
Length of the chromosomes.
encoding_type encoding
Chromosome encoding method chosen from the encoding_type enum.
crossover_type crossover
Chromosome crossover method chosen from the crossover_type enum.
mutation_type mutation
Chromosome mutation method chosen from the mutation_type enum.
selection_type selection
Chromosome selection method chosen from the selection_type enum.
replacement_type replacement
Chromosome replacement method chosen from the replacement_type enum.
T lower_boundary
Minimum value allowed for the chromosomes.
T upper_boundary
Maximum value allowed for the chromosomes.
double mutation_rate
Mutation rate for the chromosomes.
unsigned int selection_size
Amount of chromosomes to be selected in the selection phase.
double crossover_rate
Crossover rate for the selected chromosomes.
unsigned int generation
Number of the current generation.
double(* fitnessFunction)(Chromosome< T > *)
Pointer to the fitness function defined by the user. It has to return a double and accept a pointer to a chromosome.
std::default_random_engine generator
Pseudo-random generator used for generating random variables.
std::vector< std::pair< double, double > > fitnessValuesMax
Vector of paired values used for plotting the fitness function.
Detailed Description
template<class T>
class EA< T >
Definition of the EA class.
Class able to perform the evolution of a population of chromosomes. It accepts the template T to allow the chromosomes to be either int, float, double or whatever.
Todo:
Add an specialization for boolean.
Definition at line 44 of file ea.h.
Constructor & Destructor Documentation
template<class T> EA< T >::EA (int population, int size, encoding_type chromosome_encoding, T min, T max, crossover_type crossover, double crossover_rate, mutation_type mutation, double mutation_rate, selection_type selection, int selection_size, replacement_type replacement)
Class constructor.
Parameters
population Size of the population.
size Size of the chromosomes.
chromosome_encoding Encoding method of the chromosomes chosen from encoding_type.
min Minimum value allowed for the chromosomes.
max Maximum value allowed for the chromosomes.
crossover Crossover method of the chromosomes chosen from crossover_type.
crossover_rate Probability in between 0 and 1 that the crossover occurs.
mutation Mutation method of the chromosomes chosen from mutation_type.
mutation_rate Probability in between 0 and 1 that the mutation occurs.
selection Selection method of the chromosomes chosen from selection_type.
selection_size Amount of chromosomes to be selected for the crossover. It has to be an even number.
replacement Replacement method of the chromosomes chosen from replacement_type.
Definition at line 198 of file ea.cpp.
template<class T > EA< T >::~EA ()
Default destructor.
Definition at line 222 of file ea.cpp.
Member Function Documentation
template<class T > void EA< T >::evaluate ()
Method that sets the fitness value of the chromosomes in the population that haven't been evaluated yet.
Definition at line 270 of file ea.cpp.
template<class T > void EA< T >::evaluateOffspring ()
Method that sets the fitness value of the chromosomes of the offspring.
Definition at line 280 of file ea.cpp.
template<class T > void EA< T >::evaluateOffspringThreaded (unsigned int threads)
Method that sets the fitness value of the chromosomes of the offspring using multithreading.
Parameters
threads Number of threads to be used.
Definition at line 310 of file ea.cpp.
template<class T > double EA< T >::evaluateOne (Chromosome< T > * i)
Method that recieves a pointer to a chromosome and returns its fitness value using the function stored in EA::fitnessFunction.
Parameters
i Pointer to the chromosome to be evaluated.
Returns
Double containing the fitness value of the chromosome.
Definition at line 330 of file ea.cpp.
template<class T > void EA< T >::evaluateThreaded (unsigned int threads)
Method that sets the fitness value of the chromosomes in the population that haven't been evaluated yet using multithreading.
Parameters
threads Number of threads to be used.
Definition at line 290 of file ea.cpp.
template<class T > void EA< T >::evolve (unsigned int generations, int solution)
Method that performs the evolution of the population until a certain fitness value is achieved or a number of generations has passed.
Parameters
generations Maximum number of generations allowed.
solution Expected fitness value.
Deprecated:
It is desired to use the other two evolution methods since this one is outdated. It is expected to be updated soon and also to include an option with multithreading.
Definition at line 633 of file ea.cpp.
template<class T > Chromosome< T > * EA< T >::evolve (unsigned int generations)
Method that performs the evolution of the population for a certain number of generations.
Parameters
generations Number of generations to evolve.
Returns
Pointer to the best chromosome of the population after the evolution.
Definition at line 660 of file ea.cpp.
template<class T > Chromosome< T > * EA< T >::evolveThreaded (unsigned int generations, unsigned int threads)
Method that performs the evolution of the population for a certain number of generations with multithreading.
Parameters
generations Number of generations to evolve.
threads Number of threads to use.
Returns
Pointer to the best chromosome of the population after the evolution.
Bug:
After around 3500 generations the program hangs and doesn't evolve anymore.
Definition at line 706 of file ea.cpp.
Referenced by main().
template<class T > void EA< T >::initializePopulation (std::vector< Chromosome< T > * > initial_population)
Method that initializes the population of chromosomes with some given ones.
Parameters
initial_population Vector of the same size of the population defined in the constructor. It contains pointers to chromosomes.
Definition at line 249 of file ea.cpp.
template<class T > void EA< T >::printPopulation ()
Method that prints the chromosomes of the population with their values.
Definition at line 260 of file ea.cpp.
Referenced by main().
template<class T > void EA< T >::randomInitialization ()
Method that initialized the population of chromosomes randomly.
Definition at line 233 of file ea.cpp.
References Chromosome< T >::setChromosome().
Referenced by main().
template<class T > void EA< T >::replace ()
Method that fills the population with the chromosomes from the EA::selected vector and the EA::offspring vector depending on the method defined by EA::replacement_type.
Definition at line 577 of file ea.cpp.
References ELITISM, GENERATIONAL, and STEADY_STATE.
template<class T > void EA< T >::reproduce ()
Method that performs the crossover of the chromosomes stored in the EA::selected vector with the method defined in EA::crossover_type. The produced offspring is mutated and stored in the EA::offspring vector.
Definition at line 426 of file ea.cpp.
References BIT_STRING, BOUNDARY, Chromosome< T >::copyChromosome(), FLIP_BIT, GAUSSIAN, NON_UNIFORM, Chromosome< T >::setChromosome(), SINGLE_POINT, TWO_POINT, UNIFORM, and UNIFORM_CROSSOVER.
template<class T > void EA< T >::select ()
Method that selects the amount of chromosomes set by EA::selection_size with the method defined by EA::selection_type. It removes them from the EA::population vector and stores them in the EA::selected vector.
Definition at line 335 of file ea.cpp.
References RANK, ROULETTE, and TOURNAMENT.
template<class T > void EA< T >::setFitnessFunction (double(*)(Chromosome< T > *) function)
Method that sets the fitness function with which the chromosomes are evaluated.
Parameters
function Pointer to a function defined by the user. It has to return a double and accept a pointer to a chromosome.
Definition at line 227 of file ea.cpp.
Referenced by main().
template<class T> void EA< T >::setFitnessFunction (double(*)(Chromosome< T > *, int argc, char **argv) function)
Method that set the fitness function with which the chromosomes are evaluated.
Parameters
function Pointer to a function defined by the user. It has to return a double and accept a pointer to a chromosome, the number of arguments passed to the main program and the array of arguments.
Attention
This method is not implemented yet. However the definition is done for future development.
Member Data Documentation
template<class T> unsigned int EA< T >::Chromosome_size protected
Length of the chromosomes.
Definition at line 265 of file ea.h.
template<class T> crossover_type EA< T >::crossover protected
Chromosome crossover method chosen from the crossover_type enum.
Definition at line 267 of file ea.h.
template<class T> double EA< T >::crossover_rate protected
Crossover rate for the selected chromosomes.
Definition at line 275 of file ea.h.
template<class T> encoding_type EA< T >::encoding protected
Chromosome encoding method chosen from the encoding_type enum.
Definition at line 266 of file ea.h.
template<class T> double(* EA< T >::fitnessFunction) (Chromosome< T > *) protected
Pointer to the fitness function defined by the user. It has to return a double and accept a pointer to a chromosome.
Definition at line 279 of file ea.h.
template<class T> std::vector<std::pair<double, double> > EA< T >::fitnessValuesMax protected
Vector of paired values used for plotting the fitness function.
Definition at line 283 of file ea.h.
template<class T> unsigned int EA< T >::generation protected
Number of the current generation.
Definition at line 277 of file ea.h.
template<class T> std::default_random_engine EA< T >::generator protected
Pseudo-random generator used for generating random variables.
Definition at line 281 of file ea.h.
template<class T> T EA< T >::lower_boundary protected
Minimum value allowed for the chromosomes.
Definition at line 271 of file ea.h.
template<class T> mutation_type EA< T >::mutation protected
Chromosome mutation method chosen from the mutation_type enum.
Definition at line 268 of file ea.h.
template<class T> double EA< T >::mutation_rate protected
Mutation rate for the chromosomes.
Definition at line 273 of file ea.h.
template<class T> std::vector<Chromosome<T>*> EA< T >::offspring protected
Vector containing pointers to the chromosomes resultant of the crossover.
Definition at line 262 of file ea.h.
template<class T> std::vector<Chromosome<T>*> EA< T >::population protected
Vector containing pointers all the chromosomes for the actual population.
Definition at line 260 of file ea.h.
template<class T> unsigned int EA< T >::population_size protected
Size of the population.
Definition at line 264 of file ea.h.
template<class T> replacement_type EA< T >::replacement protected
Chromosome replacement method chosen from the replacement_type enum.
Definition at line 270 of file ea.h.
template<class T> std::vector<Chromosome<T>*> EA< T >::selected protected
Vector containing pointers to the selected chromosomes for crossover.
Definition at line 261 of file ea.h.
template<class T> selection_type EA< T >::selection protected
Chromosome selection method chosen from the selection_type enum.
Definition at line 269 of file ea.h.
template<class T> unsigned int EA< T >::selection_size protected
Amount of chromosomes to be selected in the selection phase.
Definition at line 274 of file ea.h.
template<class T> T EA< T >::upper_boundary protected
Maximum value allowed for the chromosomes.
Definition at line 272 of file ea.h.
The documentation for this class was generated from the following files:
ea.h
ea.cpp