# Configuration for simulation makefile
# Please add all cpp files you want to compile for this simulation
#  to the FILES variable
# You can also tell where you haved lpzrobots installed


ODEROBOTSSRCPREFIX=$(shell ode_robots-config $(CFGOPTS) --srcprefix)  #ode_robots directory
SELFORGSRCPREFIX=$(shell selforg-config $(CFGOPTS) --srcprefix)  #selforg directory

MAINDIR   = ../../../..
AMOSIIUTIL  = $(MAINDIR)/utils/rbf-framework

FILES      += 	main \
		RBFtestclass\
		$(AMOSIIUTIL)/ngnet
				
				
INC        += -I$(MAINDIR)
INC        += -I$(AMOSIIUTIL)
LIBS       = -lreadline  -lncurses
