# Configuration for simulation makefile
# Please add all cpp files you want to compile for this simulation
#  to the FILES variable
# You can also tell where you haved lpzrobots installed

ODEROBOTSSRCPREFIX=$(shell ode_robots-config $(CFGOPTS) --srcprefix)  #ode_robots directory
SELFORGSRCPREFIX=$(shell selforg-config $(CFGOPTS) --srcprefix)  #selforg directory

INCLUDE     = ../controllers
LPZROBOTS   =$(ODEROBOTSSRCPREFIX)/..



FILES      += main \
			$(INCLUDE)/muscleRunbotController
	 		
INC        += -I$(INCLUDE)	 		
LIBS         = -lreadline  -lncurses
# add this to avoid problem for 64 bit PC
LIBS = -Wl,--no-as-needed -lgsl -lgslcblas -lm
