# Configuration for simulation makefile
# Please add all cpp files you want to compile for this simulation
#  to the FILES variable
# You can also tell where you haved lpzrobots installed

GOROBOTS = ../../..

FILES      += main \
              $(GOROBOTS)/utils/ann-framework/ann \
              $(GOROBOTS)/utils/ann-framework/neuron \
              $(GOROBOTS)/utils/ann-framework/backpropagation \
			  $(GOROBOTS)/utils/ann-framework/synapse 
              

INC += -I$(GOROBOTS)

# add this to avoid problem for 64 bit PC
LIBS = -Wl,--no-as-needed -lgsl -lgslcblas -lm