# Configuration for simulation makefile
# Please add all cpp files you want to compile for this simulation
# to the FILES variable
# You can also tell where you haved lpzrobots installed

SRCDIR      = src/

GOROBOTS    = ../../../../

MYFILES    += main DelimitedFileReader EMGapproxESN
EXTFILES   += $(GOROBOTS)/examples/artificial_neural_networks/esn_network/rc_data_processing/include/networkmatrix
FILES      += $(addprefix $(SRCDIR), $(MYFILES)) $(EXTFILES)

INC        += -I$(GOROBOTS)

# add this to avoid problem for 64 bit PC
LIBS = -Wl,--no-as-needed -lgsl -lgslcblas -lm
