# Configuration for simulation makefile
# Please add all cpp files you want to compile for this simulation
#  to the FILES variable
# You can also tell where you haved lpzrobots installed

ODEROBOTSSRCPREFIX=$(shell ode_robots-config $(CFGOPTS) --srcprefix)  #ode_robots directory
SELFORGSRCPREFIX=$(shell selforg-config $(CFGOPTS) --srcprefix)  #selforg directory

GOROBOTS    = ../../..
LPZROBOTS   = $(ODEROBOTSSRCPREFIX)/..

INTERFACE	= ${LPZROBOTS}/real_robots/robots/epuck/

FILES      += main \
              examplecontroller \
              ${LPZROBOTS}/real_robots/robots/epuck/epuckbluetooth \
              ${LPZROBOTS}/real_robots/robots/epuck/SerialComm

SELFORGSRCPREFIX=$(shell selforg-config $(CFGOPTS) --srcprefix)  #selforg directory
ODEROBOTSSRCPREFIX=$(shell ode_robots-config $(CFGOPTS) --srcprefix)  #ode_robots director
SELFORG    = $(LPZROBOTS)/selforg
ODEROBOTS  = $(LPZROBOTS)/ode_robots


  
INC = -I${INTERFACE} -I${CONTROLLER} -I/usr/share/qt4/mkspecs/linux-g++-32 -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4

ADDITIONAL_LIBS  = -lQtGui -lQtCore -lpthread 

CPPFLAGS = -D_REENTRANT -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -lqt-mt
