# Configuration for simulation makefile
# Please add all cpp files you want to compile for this simulation
#  to the FILES variable
# You can also tell where you haved lpzrobots installed

GOROBOTS    = ../../..
UTILS       = $(GOROBOTS)/utils
FILES      += main 
INC        += -I$(GOROBOTS)
